### ISSUE TITLE
Add new Remote Assessment Example for Advanced Searching

### ISSUE THREAD

**Issue by joncamfield** [OpenInternet/SAFETAG#72] opened 2015-01-09 20:15 UTC
Most of the content exists, but is in resources.  Making this into an example on par with recon-ng would bring it to the right level of importance and visibility for auditors.

**Comment by elationfoundation** [comment] 2015-03-31 21:15
Closed as duplicate of issue #59

**Closed by elationfoundation** 2015-03-31 21:15 UTC
Labels: Audit
